export {default as Home} from './Home';
export {default as Dashboard} from './admin/Dashboard';
export {default as AddPost} from './admin/AddPost';
export {default as EditPost} from './admin/EditPost';
export {default as Posts} from './admin/Posts';
export {default as Settings} from './admin/Settings';
export {default as Draft} from './admin/Draft';
export {default as PostComment} from './admin/PostComment';
export {default as PostMedia} from './admin/PostMedia';
export {default as PostCatagory } from './admin/PostCatagory';
export {default as Profile} from './admin/Profile';
export {default as Messages } from './admin/Messages';
export {default as Notification } from './admin/Notification';
